# Generated by Django 5.2 on 2025-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email Đăng Nhập')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mật khẩu (Hashed)')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Tên')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Họ')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('REGULAR', 'Người dùng thường')], default='REGULAR', max_length=10, verbose_name='Loại tài khoản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tài khoản Người dùng',
                'verbose_name_plural': 'Tài khoản Người dùng',
                'db_table': 'accounts_customuser',
                'ordering': ['email'],
            },
        ),
    ]
