# Generated by Django 5.2 on 2025-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Tên Định Danh (VD: muoi_vang)')),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên Khoa Học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô Tả Đặc Điểm')),
                ('habitat', models.TextField(blank=True, null=True, verbose_name='Khu Vực Sinh Sống')),
                ('host_plants', models.TextField(blank=True, null=True, verbose_name='Loài Cây Bị Gây Hại')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Cách Xử Lý/Phòng Trừ')),
                ('active_season', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mùa Hoạt Động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Thông tin Côn trùng Tham khảo',
                'verbose_name_plural': 'Thông tin Côn trùng Tham khảo',
                'db_table': 'insect_library_insectreference',
                'ordering': ['name'],
            },
        ),
    ]
