# Generated by Django 5.2 on 2025-04-28 16:24

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploads.models.get_user_upload_path, verbose_name='File gốc')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tải lên')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='accounts.customuser', verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'File Người dùng Tải lên',
                'verbose_name_plural': 'File Người dùng Tải lên',
                'db_table': 'uploads_userupload',
                'ordering': ['-upload_time'],
            },
        ),
    ]
