# Generated by Django 5.2 on 2025-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('assigned_to_rpi', 'Đã giao cho RPi'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái xử lý'),
        ),
        migrations.AddField(
            model_name='userupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
    ]
